<TabbedCalender>:
    #size_hint: .5, .5
    do_default_tab: False
    TabbedPanelItem:
        text: 'Mon'
        id: mon
        ScrollableCalender:
    TabbedPanelItem:
        text: 'Tues'
        id: tues
        ScrollableCalender:
    TabbedPanelItem:
        text: 'Wed'
        id: wed
        ScrollableCalender:
    TabbedPanelItem:
        text: 'Thurs'
        id: thurs
        ScrollableCalender:
    TabbedPanelItem:
        text: 'Fri'
        id: fri
        ScrollableCalender:
